Add ingress template
rudderlabs/rudderstack-helm pull request #25
Opened 2021-03-02 15:38 UTC by jgrau

## Description of the change

This PR adds an optional `ingress` resource to the chart templates. The resource is disabled by default and can be enabled with `backend.ingress.enabled`.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

Fixes [#17]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

Linting generates

```
[WARNING] templates/ingress.yaml: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

But perhaps it's better to be more backwards compatible(?)

### Code review 

- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-06-02 18:28 UTC, bdashrad commented
this is useful for us, would love to get this merged

2021-06-04 01:06 UTC, bdashrad requested changes
requested some changes to update for the ingress api deprecations. 

> extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

2021-06-04 01:06 UTC, bdashrad commented on templates/ingress.yaml
> +apiVersion: extensions/v1beta1
ingress is at networking.k8s.io/v1 in 1.14+
```suggestion
apiVersion: networking.k8s.io/v1
```

2021-06-04 01:06 UTC, bdashrad commented on templates/ingress.yaml
> +              servicePort: {{ .Values.backend.service.port }}
updated to match new ingress api
```suggestion
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rudderstack.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
```

2021-06-04 01:06 UTC, bdashrad commented on values.yaml
> +    annotations:
```suggestion
    annotations: {}
```

2021-06-04 01:06 UTC, bdashrad commented on values.yaml
> +    hostname: "rudderstack.local"
```suggestion
    hostname: "rudderstack.local"
    # optional override for tls secret name
    # secretName: rudderstack-tls
```

2021-06-07 16:47 UTC, xavidop commented
hello! @jgrau and @bdashrad what is the current status of this PR? we need this, I can contribute it as well the changes requested, what is needed for this PR?

2021-06-07 18:16 UTC, jgrau commented
> hello! @jgrau and @bdashrad what is the current status of this PR? we need this, I can contribute it as well the changes requested, what is needed for this PR?

Current status: I merged the requested changes (Thank you, @bdashrad ❤️ ) but the PR has been waiting for review since I created it. Merging is blocked until I get 2 approving reviews.

2021-06-07 18:27 UTC, bdashrad commented
I just asked about trying to get this merged in the slack support chat, hopefully that gets some movement.

2021-06-09 23:08 UTC, immber commented
Here to add a +1 to please merge this! Anybody trying to use rudderstack's helm chart on GKE needs this option.

2021-06-15 09:23 UTC, AkhileshK8y approved these changes

2021-06-15 12:04 UTC, MiteshSharma approved these changes

2021-06-15 12:04 UTC, merged

2021-06-15 12:05 UTC, SumanthPuram commented
@jgrau @immber @bdashrad Apologies for the delay. Just merged this.