feat: enable/disable postgres
rudderlabs/rudderstack-helm pull request #28
Opened 2021-06-07 17:07 UTC by xavidop

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-06-07 17:14 UTC, xavidop commented
Implements changes requested on https://github.com/rudderlabs/rudderstack-helm/pull/28

2021-06-07 18:28 UTC, bdashrad commented on templates/_helpers.tpl
> +{{- define "postgresql.host.main" -}}
this is a nice way to implement this.

2021-06-15 14:27 UTC, bdashrad commented
This would be great to have, and fixes #16

2021-07-13 16:48 UTC, lokey requested changes

2021-07-13 16:48 UTC, lokey commented on templates/statefulset.yaml
>              value: "This is expected to be set by docker entrypoint script"
`JOBS_DB_HOST` env is how the server connects to the postgres db. This env value is overwritten by the docker entrypoint script in server if `COMPUTE_DB_HOST_IN_K8S`.
When postgres.enabled is false, we should have this env pointing to the external db's host that is used.
We can do this by having an extra config value like `values.backend.exteranlDBHost`.

2021-09-03 16:19 UTC, closed without merging