Support external Postgresql database server
rudderlabs/rudderstack-helm pull request #35
Opened 2021-09-09 17:05 UTC by azhelev

## Description of the change

Adds support for using external Postgresql server

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-10-11 06:24 UTC, nauxliu commented
Will there be a problem if multiple workers share one Postgresql instance? as far as I know every worker has its own Postgresql.

2021-10-19 20:15 UTC, Dr4il approved these changes
Nice work

2021-12-21 14:46 UTC, snarkychef requested changes

2021-12-21 14:46 UTC, snarkychef commented on templates/statefulset.yaml
> +            {{- if .Values.external_postgresql.enabled }}
Having two boolean fields viz. external_postgresql.enabled and postgresql.enabled can cause consistency issues. Does it make sense to use just postgresql.enabled?

2021-12-21 14:46 UTC, snarkychef commented on templates/statefulset.yaml
> +            value: "{{ .Values.external_postgresql.postgresqlPort }}"
Add default port as 5432?

2021-12-21 14:46 UTC, snarkychef commented on templates/statefulset.yaml
> +            value: "{{ .Values.external_postgresql.postgresqlSslMode }}"
Add default value `disable` ?

2021-12-21 14:46 UTC, snarkychef commented on values.yaml
> +  postgresqlHost: example.server
comment out this block? and keep values only for variables which have default values defined in code.

2021-12-21 14:46 UTC, snarkychef commented on Chart.yaml
> +  repository: https://charts.bitnami.com/bitnami
instead of helm repository, can we use path based chart dependency as we already have code in this repo.

2022-04-07 16:53 UTC, ldaugusto commented
> Will there be a problem if multiple workers share one Postgresql instance? as far as I know every worker has its own Postgresql.

That's a good point. If a single db instance can handle multiple servers, why does the chart load a new postgres for every server instance.

2023-01-14 05:45 UTC, gitcommitshow commented
@azhelev can you please check the comments in this PR

2023-01-14 05:46 UTC, gitcommitshow commented
As shared by @psrikanth88, this PR has some unaddressed comments. And it would work with only one replica of statefulset. If there are multiple, it needs extra configuration support in our code to use different schema in same external postgres for each replica.

2023-01-14 15:22 UTC, azhelev commented
I don't use this anymore, i have no interest in completing this PR. If someone wants to take it up feel free.

2023-01-14 15:22 UTC, closed without merging